### ISSUE TITLE
Incompatibility with mkdocs 1.5.0

### ISSUE THREAD

**Issue by martymichal** [inuits/mkdocs-subsite#4]
**Description of the problem**

A new version of mkdocs was [released](https://www.mkdocs.org/about/release-notes/#version-150-2023-07-26) and with it changed in some way handling of page files. This causes sites added to a central site using this plugin to be excluded from the final build.

In the build log one can see messages like:

```
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
INFO    -  A reference to '../subsite/foo.md' is included in the 'nav' configuration, but this file is excluded from the built site.
```

**Current behaviour**

Subsites are excluded from the final build.

**Desired behaviour**

Subsites are included in the final build.

**Comment by zarybnicky** [comment]
Resolved in 1.1.3
